# action.yml
name: 'JAVA 7 And MAVEN Action'
author: 'Codrut Predoi <codrut.predoi@yahoo.com>'
description: 'build tool for GitHub action with JAVA 7 and Maven'
inputs:
  command:
    description: 'Command to run'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}

branding:
  icon: 'package'
  color: 'blue'
