#!/bin/sh

set -x

COMMAND=$1
ARTIFACTORY_RELEASE_USERNAME_VARIABLE=$2
ARTIFACTORY_RELEASE_USERNAME_VAL=$3
ARTIFACTORY_SNAPSHOTS_USERNAME_VARIABLE=$4
ARTIFACTORY_SNAPSHOTS_USERNAME_VAL=$5
if [[ -z "${INIT_COMMAND}" ]]; then
  echo "No Init command was procided"
else
  ${INIT_COMMAND}
fi

if [[ -z "${6}" ]]; then
  echo "No settings file was provided"
  mvn $1 -D"${ARTIFACTORY_RELEASE_USERNAME_VARIABLE}=${ARTIFACTORY_RELEASE_USERNAME_VAL}" -D"${ARTIFACTORY_SNAPSHOTS_USERNAME_VARIABLE}=${ARTIFACTORY_SNAPSHOTS_USERNAME_VAL}"
else
  SETTINGS=$6
  mvn $1 -s ${SETTINGS} -D"${ARTIFACTORY_RELEASE_USERNAME_VARIABLE}=${ARTIFACTORY_RELEASE_USERNAME_VAL}" -D"${ARTIFACTORY_SNAPSHOTS_USERNAME_VARIABLE}=${ARTIFACTORY_SNAPSHOTS_USERNAME_VAL}"
fi